### ISSUE TITLE
whatsapp支持手机离线发送消息正在公测，我使用测试版本发现现在的二维码不能用，怎么办？

### ISSUE THREAD

**Issue by zhengshengjie666** [JicuNull/WhatsJava#19]
https://faq.whatsapp.com/general/download-and-installation/about-multi-device-beta

**Comment by hamedsharifi** [comment]
Library doesn't work with multi device enabled. Get error below:
`Caused by: java.lang.NullPointerException
	at icu.jnet.whatsjava.helper.Utils.encodeValidJson(Utils.java:55)
	at icu.jnet.whatsjava.whatsapp.WABackendConnector.initOrRestoreSession(WABackendConnector.java:101)
	at icu.jnet.whatsjava.whatsapp.WABackendConnector.openConnection(WABackendConnector.java:58)`
